### ISSUE TITLE
Instructions don't match solution | Chapter 5 Exercise 7

### ISSUE THREAD

**Issue by Hadrien-lcrx** [datacamp/courses-introduction-to-shell#98]
In [How can one shell script do many things?](https://campus.datacamp.com/courses/introduction-to-shell-for-data-science/creating-new-tools?ex=7), instructions state:

"Use Nano to edit the script `range.sh` and replace the `____` placeholders so that it lists the names and number of lines in all of the files given on the command line without showing the total number of lines in all files. (Do not try to subtract the column header lines from the files.)"

The solution is:
`cp /solutions/range-1.sh range.sh`

This command copies the file, it doesn't edit anything. This is a similar issue to #97.

### Recommendation
Update instructions, or update solution.

### Screenshot
![image](https://user-images.githubusercontent.com/22552805/33798014-c959f2f8-dd11-11e7-8a72-5ab9cb2d8827.png)

Cf faik.200@gmail.com, #63318
Cc @bakera81

**Comment by Karthi9934** [comment]
Facing similar issue have given feedback as well. Can you please update this solution
